name: Docker Build and Run

on:
  push

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Run Docker container
        run: docker run -d --name my-container -p 8080:80 my-docker-image
